<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>Frends SecureEnvelope Library</Title>
        <Authors>Lars Scheibling &lt;Hoglandets IT&gt;</Authors>
        <Description> </Description>
        <Version>2.0.1</Version>
    </PropertyGroup>
    <ItemGroup>
      <None Include="FrendsTaskMetadata.json" Pack="true" PackagePath="/">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
    </ItemGroup>
</Project>
